version: "3.8"  # optional since v1.27.0
services:
  web:
    build: .
    image: apidemo11
    ports:
      - "8090:8090"
    volumes:
      - .:/app
      - logvolume01:/var/log
volumes:
  logvolume01: {}
